language: python
python:
  - "3.8"

addons:
  firefox: latest

install:
  # При установке firefox-geckodriver через apt-get,
  # путь к нему будет автоматически добавлен в $PATH.
  # Тогда не нужно передавать путь в webdriver.Firefox(executable_path).
  #- sudo apt-get install firefox-geckodriver
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest ./tests/* --cov

notifications:
  email: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

codecov: true